### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET https://nominatim.openstreetmap.org/search?q=Kek&format=json&limit=1


###
GET https://nominatim.openstreetmap.org/search?q=11%20%D0%9A%D0%B0%D1%80%D0%B1%D0%BE%D0%BB%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%2C%20%D0%9A%D0%B5%D0%BC%D0%B5%D1%80%D0%BE%D0%B2%D0%BE&format=json&addressdetails=1


###
GET https://api.openstreetmap.org/api/0.6/way/92904694.json


29 улица Николая Островского Кемерово

###
POST http://localhost:8081/api/v1/building/info
Content-Type: application/json

{
  "address": "Красная Горка, 19 Кемерово"
}
