name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: city-snap-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.3"
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff
        run: poetry run ruff check

  test:
    name: Pytest
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: city-snap-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.3"
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pytest
        run: poetry run pytest
